name: Proyecto Databricks

on:
  push:
    branches:
      - main

jobs:
  validar:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Validar proyecto
        run: |
          echo "Proyecto Databricks validado correctamente"
